# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


from .items import items_dict
from .types.locations import AccessInfo, LocationData
from .types.shops import ShopData
from .types.condition import *
from .locations import locations_dict

shop_dict: dict[str, ShopData] = {
    'Rookie Harbor Items': ShopData(internal_name='rookieHarborItems', name='Rookie Harbor Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    'Rookie Harbor Items (Post-Blue Ice)': ShopData(internal_name='rookieHarborItems', name='Rookie Harbor Items (Post-Blue Ice)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    'Rookie Harbor Items (Post-Red Flame)': ShopData(internal_name='rookieHarborItems', name='Rookie Harbor Items (Post-Red Flame)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Rookie Harbor Items (Post-Green Seed)': ShopData(internal_name='rookieHarborItems', name='Rookie Harbor Items (Post-Green Seed)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Green Seed Shade', amount=1)])),
    'Rookie Harbor Weapons': ShopData(internal_name='rookieHarborWeapons', name='Rookie Harbor Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    'Rookie Harbor Weapons (Post-Red Flame)': ShopData(internal_name='rookieHarborWeapons', name='Rookie Harbor Weapons (Post-Red Flame)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Rookie Harbor North Weapons': ShopData(internal_name='rookieHarborWeaponsNorth', name='Rookie Harbor North Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '19', 'open': 'open8'})),
    "Tara's Shop": ShopData(internal_name='rookieHarborTara', name="Tara's Shop", metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    'Rookie Harbor Backer Items': ShopData(internal_name='rookieBacker', name='Rookie Harbor Backer Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '19', 'open': 'open8'})),
    'Bergen Village Items': ShopData(internal_name='bergenVillageItems', name='Bergen Village Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    'Bergen Village Items (Post-Blue Ice)': ShopData(internal_name='bergenVillageItems', name='Bergen Village Items (Post-Blue Ice)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    'Bergen Village Items (Post-Red Flame)': ShopData(internal_name='bergenVillageItems', name='Bergen Village Items (Post-Red Flame)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Bergen Village Items (Post-Green Seed)': ShopData(internal_name='bergenVillageItems', name='Bergen Village Items (Post-Green Seed)', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Green Seed Shade', amount=1)])),
    'Bergen Village Weapons': ShopData(internal_name='bergenVillageWeapons', name='Bergen Village Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    "Hermit's Hut": ShopData(internal_name='bergenHermit', name="Hermit's Hut", metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    "Ba'kii Kum Items": ShopData(internal_name='bakiItems', name="Ba'kii Kum Items", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    "Ba'kii Kum Items (Post-Blue Ice)": ShopData(internal_name='bakiItems', name="Ba'kii Kum Items (Post-Blue Ice)", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    "Ba'kii Kum Items (Post-Green Seed)": ShopData(internal_name='bakiItems', name="Ba'kii Kum Items (Post-Green Seed)", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    "Ba'kii Kum Weapons": ShopData(internal_name='bakiWeapons', name="Ba'kii Kum Weapons", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    'Basin Keep Vending Machine': ShopData(internal_name='basinVendingMachines', name='Basin Keep Vending Machine', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Basin Keep Items': ShopData(internal_name='basinItems', name='Basin Keep Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Basin Keep Weapons': ShopData(internal_name='basinWeapons', name='Basin Keep Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Calzone Shop': ShopData(internal_name='basinMushroom', name='Calzone Shop', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'}, cond=[ItemCondition(item_name='Wave', amount=1)])),
    'Sapphire Ridge Weapons': ShopData(internal_name='sapphireWeapons', name='Sapphire Ridge Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '31', 'open': 'open16'})),
    'Sapphire Ridge Items': ShopData(internal_name='sapphireItems', name='Sapphire Ridge Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '31', 'open': 'open16'})),
}

per_shop_locations: dict[str, dict[int, LocationData]] = {
    "Rookie Harbor Items": {
        1: locations_dict['Rookie Harbor Items - Sandwich Slot'],
        27: locations_dict['Rookie Harbor Items - Hi-Sandwich Slot'],
        2: locations_dict['Rookie Harbor Items - Green Leaf Tea Slot'],
        366: locations_dict['Rookie Harbor Items - Just Water Slot'],
        64: locations_dict['Rookie Harbor Items - Spicy Bun Slot'],
        70: locations_dict['Rookie Harbor Items - Fruit Drink Slot'],
        73: locations_dict['Rookie Harbor Items - Rice Cracker Slot'],
        67: locations_dict['Rookie Harbor Items - Veggie Sticks Slot'],
    },
    "Rookie Harbor Items (Post-Blue Ice)": {
        353: locations_dict['Rookie Harbor Items (Post-Blue Ice) - Kebab Roll Slot'],
        355: locations_dict['Rookie Harbor Items (Post-Blue Ice) - Meaty Risotto Slot'],
    },
    "Rookie Harbor Items (Post-Red Flame)": {
        110: locations_dict['Rookie Harbor Items (Post-Red Flame) - Bergen Ice Cream Slot'],
        165: locations_dict['Rookie Harbor Items (Post-Red Flame) - Sweet Lemonjuice Slot'],
    },
    "Rookie Harbor Items (Post-Green Seed)": {
        290: locations_dict['Rookie Harbor Items (Post-Green Seed) - Salted Peanuts Slot'],
        291: locations_dict["Rookie Harbor Items (Post-Green Seed) - Cup o' Coffee Slot"],
        331: locations_dict['Rookie Harbor Items (Post-Green Seed) - Snack Mix Slot'],
    },
    "Rookie Harbor Weapons": {
        31: locations_dict['Rookie Harbor Weapons - Bronze Goggles Slot'],
        29: locations_dict['Rookie Harbor Weapons - Bronze Edge Slot'],
        30: locations_dict['Rookie Harbor Weapons - Bronze Mail Slot'],
        32: locations_dict['Rookie Harbor Weapons - Bronze Boots Slot'],
        118: locations_dict['Rookie Harbor Weapons - Iron Goggles Slot'],
        113: locations_dict['Rookie Harbor Weapons - Iron Edge Slot'],
        122: locations_dict['Rookie Harbor Weapons - Iron Mail Slot'],
        121: locations_dict['Rookie Harbor Weapons - Iron Boots Slot'],
    },
    "Rookie Harbor Weapons (Post-Red Flame)": {
        264: locations_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Goggles Slot'],
        266: locations_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Edge Slot'],
        268: locations_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Mail Slot'],
        270: locations_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Boots Slot'],
    },
    "Rookie Harbor North Weapons": {
        204: locations_dict['Rookie Harbor North Weapons - Steel Goggles Slot'],
        205: locations_dict['Rookie Harbor North Weapons - Steel Edge Slot'],
        206: locations_dict['Rookie Harbor North Weapons - Steel Mail Slot'],
        207: locations_dict['Rookie Harbor North Weapons - Steel Boots Slot'],
        264: locations_dict['Rookie Harbor North Weapons - Silver Goggles Slot'],
        266: locations_dict['Rookie Harbor North Weapons - Silver Edge Slot'],
        268: locations_dict['Rookie Harbor North Weapons - Silver Mail Slot'],
        270: locations_dict['Rookie Harbor North Weapons - Silver Boots Slot'],
    },
    "Tara's Shop": {
        1: locations_dict["Tara's Shop - Sandwich Slot"],
    },
    "Rookie Harbor Backer Items": {
        382: locations_dict['Rookie Harbor Backer Items - Rising Super Star Slot'],
        490: locations_dict['Rookie Harbor Backer Items - Dk Pepper Slot'],
        491: locations_dict['Rookie Harbor Backer Items - Cheese Spaetzle Slot'],
        315: locations_dict['Rookie Harbor Backer Items - Maultasche Slot'],
        493: locations_dict['Rookie Harbor Backer Items - Durian Slot'],
        494: locations_dict['Rookie Harbor Backer Items - PengoPop Slot'],
        495: locations_dict['Rookie Harbor Backer Items - Spicy Beat-0-Type Slot'],
        316: locations_dict['Rookie Harbor Backer Items - Werewolf Stick Slot'],
        516: locations_dict['Rookie Harbor Backer Items - Mooncake Slot'],
        496: locations_dict['Rookie Harbor Backer Items - Guacamole Toast Slot'],
        551: locations_dict['Rookie Harbor Backer Items - Willis Waldmahl Slot'],
        637: locations_dict['Rookie Harbor Backer Items - Pumpkin Spice Cof. Slot'],
    },
    "Bergen Village Items": {
        1: locations_dict['Bergen Village Items - Sandwich Slot'],
        27: locations_dict['Bergen Village Items - Hi-Sandwich Slot'],
        2: locations_dict['Bergen Village Items - Green Leaf Tea Slot'],
        366: locations_dict['Bergen Village Items - Just Water Slot'],
        64: locations_dict['Bergen Village Items - Spicy Bun Slot'],
        70: locations_dict['Bergen Village Items - Fruit Drink Slot'],
        73: locations_dict['Bergen Village Items - Rice Cracker Slot'],
        67: locations_dict['Bergen Village Items - Veggie Sticks Slot'],
    },
    "Bergen Village Items (Post-Blue Ice)": {
        353: locations_dict['Bergen Village Items (Post-Blue Ice) - Kebab Roll Slot'],
        355: locations_dict['Bergen Village Items (Post-Blue Ice) - Meaty Risotto Slot'],
    },
    "Bergen Village Items (Post-Red Flame)": {
        110: locations_dict['Bergen Village Items (Post-Red Flame) - Bergen Ice Cream Slot'],
        165: locations_dict['Bergen Village Items (Post-Red Flame) - Sweet Lemonjuice Slot'],
    },
    "Bergen Village Items (Post-Green Seed)": {
        290: locations_dict['Bergen Village Items (Post-Green Seed) - Salted Peanuts Slot'],
        291: locations_dict["Bergen Village Items (Post-Green Seed) - Cup o' Coffee Slot"],
        331: locations_dict['Bergen Village Items (Post-Green Seed) - Snack Mix Slot'],
    },
    "Bergen Village Weapons": {
        118: locations_dict['Bergen Village Weapons - Iron Goggles Slot'],
        113: locations_dict['Bergen Village Weapons - Iron Edge Slot'],
        122: locations_dict['Bergen Village Weapons - Iron Mail Slot'],
        121: locations_dict['Bergen Village Weapons - Iron Boots Slot'],
    },
    "Hermit's Hut": {
        77: locations_dict["Hermit's Hut - Chili Con Carne Slot"],
        165: locations_dict["Hermit's Hut - Sweet Lemonjuice Slot"],
        3: locations_dict["Hermit's Hut - Sweet Berry Tea Slot"],
    },
    "Ba'kii Kum Items": {
        1: locations_dict["Ba'kii Kum Items - Sandwich Slot"],
        27: locations_dict["Ba'kii Kum Items - Hi-Sandwich Slot"],
        2: locations_dict["Ba'kii Kum Items - Green Leaf Tea Slot"],
        366: locations_dict["Ba'kii Kum Items - Just Water Slot"],
        64: locations_dict["Ba'kii Kum Items - Spicy Bun Slot"],
        70: locations_dict["Ba'kii Kum Items - Fruit Drink Slot"],
        73: locations_dict["Ba'kii Kum Items - Rice Cracker Slot"],
        67: locations_dict["Ba'kii Kum Items - Veggie Sticks Slot"],
        110: locations_dict["Ba'kii Kum Items - Bergen Ice Cream Slot"],
        165: locations_dict["Ba'kii Kum Items - Sweet Lemonjuice Slot"],
    },
    "Ba'kii Kum Items (Post-Blue Ice)": {
        353: locations_dict["Ba'kii Kum Items (Post-Blue Ice) - Kebab Roll Slot"],
        355: locations_dict["Ba'kii Kum Items (Post-Blue Ice) - Meaty Risotto Slot"],
    },
    "Ba'kii Kum Items (Post-Green Seed)": {
        290: locations_dict["Ba'kii Kum Items (Post-Green Seed) - Salted Peanuts Slot"],
        291: locations_dict["Ba'kii Kum Items (Post-Green Seed) - Cup o' Coffee Slot"],
        331: locations_dict["Ba'kii Kum Items (Post-Green Seed) - Snack Mix Slot"],
    },
    "Ba'kii Kum Weapons": {
        118: locations_dict["Ba'kii Kum Weapons - Iron Goggles Slot"],
        113: locations_dict["Ba'kii Kum Weapons - Iron Edge Slot"],
        122: locations_dict["Ba'kii Kum Weapons - Iron Mail Slot"],
        121: locations_dict["Ba'kii Kum Weapons - Iron Boots Slot"],
        204: locations_dict["Ba'kii Kum Weapons - Steel Goggles Slot"],
        205: locations_dict["Ba'kii Kum Weapons - Steel Edge Slot"],
        206: locations_dict["Ba'kii Kum Weapons - Steel Mail Slot"],
        207: locations_dict["Ba'kii Kum Weapons - Steel Boots Slot"],
    },
    "Basin Keep Vending Machine": {
        1: locations_dict['Basin Keep Vending Machine - Sandwich Slot'],
        27: locations_dict['Basin Keep Vending Machine - Hi-Sandwich Slot'],
        2: locations_dict['Basin Keep Vending Machine - Green Leaf Tea Slot'],
        366: locations_dict['Basin Keep Vending Machine - Just Water Slot'],
        64: locations_dict['Basin Keep Vending Machine - Spicy Bun Slot'],
        70: locations_dict['Basin Keep Vending Machine - Fruit Drink Slot'],
        73: locations_dict['Basin Keep Vending Machine - Rice Cracker Slot'],
        67: locations_dict['Basin Keep Vending Machine - Veggie Sticks Slot'],
        110: locations_dict['Basin Keep Vending Machine - Bergen Ice Cream Slot'],
        165: locations_dict['Basin Keep Vending Machine - Sweet Lemonjuice Slot'],
        290: locations_dict['Basin Keep Vending Machine - Salted Peanuts Slot'],
        291: locations_dict["Basin Keep Vending Machine - Cup o' Coffee Slot"],
        331: locations_dict['Basin Keep Vending Machine - Snack Mix Slot'],
        353: locations_dict['Basin Keep Vending Machine - Kebab Roll Slot'],
        355: locations_dict['Basin Keep Vending Machine - Meaty Risotto Slot'],
    },
    "Basin Keep Items": {
        1: locations_dict['Basin Keep Items - Sandwich Slot'],
        27: locations_dict['Basin Keep Items - Hi-Sandwich Slot'],
        2: locations_dict['Basin Keep Items - Green Leaf Tea Slot'],
        366: locations_dict['Basin Keep Items - Just Water Slot'],
        353: locations_dict['Basin Keep Items - Kebab Roll Slot'],
        355: locations_dict['Basin Keep Items - Meaty Risotto Slot'],
        64: locations_dict['Basin Keep Items - Spicy Bun Slot'],
        70: locations_dict['Basin Keep Items - Fruit Drink Slot'],
        73: locations_dict['Basin Keep Items - Rice Cracker Slot'],
        67: locations_dict['Basin Keep Items - Veggie Sticks Slot'],
        110: locations_dict['Basin Keep Items - Bergen Ice Cream Slot'],
        165: locations_dict['Basin Keep Items - Sweet Lemonjuice Slot'],
        290: locations_dict['Basin Keep Items - Salted Peanuts Slot'],
        291: locations_dict["Basin Keep Items - Cup o' Coffee Slot"],
        331: locations_dict['Basin Keep Items - Snack Mix Slot'],
    },
    "Basin Keep Weapons": {
        264: locations_dict['Basin Keep Weapons - Silver Goggles Slot'],
        266: locations_dict['Basin Keep Weapons - Silver Edge Slot'],
        268: locations_dict['Basin Keep Weapons - Silver Mail Slot'],
        270: locations_dict['Basin Keep Weapons - Silver Boots Slot'],
        265: locations_dict['Basin Keep Weapons - Titan Goggles Slot'],
        267: locations_dict['Basin Keep Weapons - Titan Edge Slot'],
        269: locations_dict['Basin Keep Weapons - Titan Mail Slot'],
        271: locations_dict['Basin Keep Weapons - Titan Boots Slot'],
    },
    "Calzone Shop": {
        346: locations_dict['Calzone Shop - One Up Slot'],
    },
    "Sapphire Ridge Weapons": {
        265: locations_dict['Sapphire Ridge Weapons - Titan Goggles Slot'],
        267: locations_dict['Sapphire Ridge Weapons - Titan Edge Slot'],
        269: locations_dict['Sapphire Ridge Weapons - Titan Mail Slot'],
        271: locations_dict['Sapphire Ridge Weapons - Titan Boots Slot'],
        393: locations_dict['Sapphire Ridge Weapons - Cobalt Goggles Slot'],
        394: locations_dict['Sapphire Ridge Weapons - Cobalt Edge Slot'],
        395: locations_dict['Sapphire Ridge Weapons - Cobalt Mail Slot'],
        396: locations_dict['Sapphire Ridge Weapons - Cobalt Boots Slot'],
    },
    "Sapphire Ridge Items": {
        1: locations_dict['Sapphire Ridge Items - Sandwich Slot'],
        27: locations_dict['Sapphire Ridge Items - Hi-Sandwich Slot'],
        2: locations_dict['Sapphire Ridge Items - Green Leaf Tea Slot'],
        366: locations_dict['Sapphire Ridge Items - Just Water Slot'],
        353: locations_dict['Sapphire Ridge Items - Kebab Roll Slot'],
        355: locations_dict['Sapphire Ridge Items - Meaty Risotto Slot'],
        64: locations_dict['Sapphire Ridge Items - Spicy Bun Slot'],
        70: locations_dict['Sapphire Ridge Items - Fruit Drink Slot'],
        73: locations_dict['Sapphire Ridge Items - Rice Cracker Slot'],
        67: locations_dict['Sapphire Ridge Items - Veggie Sticks Slot'],
        110: locations_dict['Sapphire Ridge Items - Bergen Ice Cream Slot'],
        165: locations_dict['Sapphire Ridge Items - Sweet Lemonjuice Slot'],
        290: locations_dict['Sapphire Ridge Items - Salted Peanuts Slot'],
        291: locations_dict["Sapphire Ridge Items - Cup o' Coffee Slot"],
        331: locations_dict['Sapphire Ridge Items - Snack Mix Slot'],
    },
    
}

global_shop_locations: dict[int, LocationData] = {
    1: locations_dict['Global Sandwich Slot'],
    27: locations_dict['Global Hi-Sandwich Slot'],
    2: locations_dict['Global Green Leaf Tea Slot'],
    366: locations_dict['Global Just Water Slot'],
    64: locations_dict['Global Spicy Bun Slot'],
    70: locations_dict['Global Fruit Drink Slot'],
    73: locations_dict['Global Rice Cracker Slot'],
    67: locations_dict['Global Veggie Sticks Slot'],
    353: locations_dict['Global Kebab Roll Slot'],
    355: locations_dict['Global Meaty Risotto Slot'],
    110: locations_dict['Global Bergen Ice Cream Slot'],
    165: locations_dict['Global Sweet Lemonjuice Slot'],
    290: locations_dict['Global Salted Peanuts Slot'],
    291: locations_dict["Global Cup o' Coffee Slot"],
    331: locations_dict['Global Snack Mix Slot'],
    31: locations_dict['Global Bronze Goggles Slot'],
    29: locations_dict['Global Bronze Edge Slot'],
    30: locations_dict['Global Bronze Mail Slot'],
    32: locations_dict['Global Bronze Boots Slot'],
    118: locations_dict['Global Iron Goggles Slot'],
    113: locations_dict['Global Iron Edge Slot'],
    122: locations_dict['Global Iron Mail Slot'],
    121: locations_dict['Global Iron Boots Slot'],
    264: locations_dict['Global Silver Goggles Slot'],
    266: locations_dict['Global Silver Edge Slot'],
    268: locations_dict['Global Silver Mail Slot'],
    270: locations_dict['Global Silver Boots Slot'],
    204: locations_dict['Global Steel Goggles Slot'],
    205: locations_dict['Global Steel Edge Slot'],
    206: locations_dict['Global Steel Mail Slot'],
    207: locations_dict['Global Steel Boots Slot'],
    382: locations_dict['Global Rising Super Star Slot'],
    490: locations_dict['Global Dk Pepper Slot'],
    491: locations_dict['Global Cheese Spaetzle Slot'],
    315: locations_dict['Global Maultasche Slot'],
    493: locations_dict['Global Durian Slot'],
    494: locations_dict['Global PengoPop Slot'],
    495: locations_dict['Global Spicy Beat-0-Type Slot'],
    316: locations_dict['Global Werewolf Stick Slot'],
    516: locations_dict['Global Mooncake Slot'],
    496: locations_dict['Global Guacamole Toast Slot'],
    551: locations_dict['Global Willis Waldmahl Slot'],
    637: locations_dict['Global Pumpkin Spice Cof. Slot'],
    77: locations_dict['Global Chili Con Carne Slot'],
    3: locations_dict['Global Sweet Berry Tea Slot'],
    265: locations_dict['Global Titan Goggles Slot'],
    267: locations_dict['Global Titan Edge Slot'],
    269: locations_dict['Global Titan Mail Slot'],
    271: locations_dict['Global Titan Boots Slot'],
    346: locations_dict['Global One Up Slot'],
    393: locations_dict['Global Cobalt Goggles Slot'],
    394: locations_dict['Global Cobalt Edge Slot'],
    395: locations_dict['Global Cobalt Mail Slot'],
    396: locations_dict['Global Cobalt Boots Slot'],
}

shop_unlock_by_id = {
    1: items_dict['Global Sandwich Slot Unlock', 1],
    27: items_dict['Global Hi-Sandwich Slot Unlock', 1],
    2: items_dict['Global Green Leaf Tea Slot Unlock', 1],
    366: items_dict['Global Just Water Slot Unlock', 1],
    64: items_dict['Global Spicy Bun Slot Unlock', 1],
    70: items_dict['Global Fruit Drink Slot Unlock', 1],
    73: items_dict['Global Rice Cracker Slot Unlock', 1],
    67: items_dict['Global Veggie Sticks Slot Unlock', 1],
    353: items_dict['Global Kebab Roll Slot Unlock', 1],
    355: items_dict['Global Meaty Risotto Slot Unlock', 1],
    110: items_dict['Global Bergen Ice Cream Slot Unlock', 1],
    165: items_dict['Global Sweet Lemonjuice Slot Unlock', 1],
    290: items_dict['Global Salted Peanuts Slot Unlock', 1],
    291: items_dict["Global Cup o' Coffee Slot Unlock", 1],
    331: items_dict['Global Snack Mix Slot Unlock', 1],
    31: items_dict['Global Bronze Goggles Slot Unlock', 1],
    29: items_dict['Global Bronze Edge Slot Unlock', 1],
    30: items_dict['Global Bronze Mail Slot Unlock', 1],
    32: items_dict['Global Bronze Boots Slot Unlock', 1],
    118: items_dict['Global Iron Goggles Slot Unlock', 1],
    113: items_dict['Global Iron Edge Slot Unlock', 1],
    122: items_dict['Global Iron Mail Slot Unlock', 1],
    121: items_dict['Global Iron Boots Slot Unlock', 1],
    264: items_dict['Global Silver Goggles Slot Unlock', 1],
    266: items_dict['Global Silver Edge Slot Unlock', 1],
    268: items_dict['Global Silver Mail Slot Unlock', 1],
    270: items_dict['Global Silver Boots Slot Unlock', 1],
    204: items_dict['Global Steel Goggles Slot Unlock', 1],
    205: items_dict['Global Steel Edge Slot Unlock', 1],
    206: items_dict['Global Steel Mail Slot Unlock', 1],
    207: items_dict['Global Steel Boots Slot Unlock', 1],
    382: items_dict['Global Rising Super Star Slot Unlock', 1],
    490: items_dict['Global Dk Pepper Slot Unlock', 1],
    491: items_dict['Global Cheese Spaetzle Slot Unlock', 1],
    315: items_dict['Global Maultasche Slot Unlock', 1],
    493: items_dict['Global Durian Slot Unlock', 1],
    494: items_dict['Global PengoPop Slot Unlock', 1],
    495: items_dict['Global Spicy Beat-0-Type Slot Unlock', 1],
    316: items_dict['Global Werewolf Stick Slot Unlock', 1],
    516: items_dict['Global Mooncake Slot Unlock', 1],
    496: items_dict['Global Guacamole Toast Slot Unlock', 1],
    551: items_dict['Global Willis Waldmahl Slot Unlock', 1],
    637: items_dict['Global Pumpkin Spice Cof. Slot Unlock', 1],
    77: items_dict['Global Chili Con Carne Slot Unlock', 1],
    3: items_dict['Global Sweet Berry Tea Slot Unlock', 1],
    265: items_dict['Global Titan Goggles Slot Unlock', 1],
    267: items_dict['Global Titan Edge Slot Unlock', 1],
    269: items_dict['Global Titan Mail Slot Unlock', 1],
    271: items_dict['Global Titan Boots Slot Unlock', 1],
    346: items_dict['Global One Up Slot Unlock', 1],
    393: items_dict['Global Cobalt Goggles Slot Unlock', 1],
    394: items_dict['Global Cobalt Edge Slot Unlock', 1],
    395: items_dict['Global Cobalt Mail Slot Unlock', 1],
    396: items_dict['Global Cobalt Boots Slot Unlock', 1],
}

shop_unlock_by_shop = {
    'rookieHarborItems': items_dict['Rookie Harbor Items Unlock', 1],
    'rookieHarborWeapons': items_dict['Rookie Harbor Weapons Unlock', 1],
    'rookieHarborWeaponsNorth': items_dict['Rookie Harbor North Weapons Unlock', 1],
    'rookieHarborTara': items_dict["Tara's Shop Unlock", 1],
    'rookieBacker': items_dict['Rookie Harbor Backer Items Unlock', 1],
    'bergenVillageItems': items_dict['Bergen Village Items Unlock', 1],
    'bergenVillageWeapons': items_dict['Bergen Village Weapons Unlock', 1],
    'bergenHermit': items_dict["Hermit's Hut Unlock", 1],
    'bakiItems': items_dict["Ba'kii Kum Items Unlock", 1],
    'bakiWeapons': items_dict["Ba'kii Kum Weapons Unlock", 1],
    'basinVendingMachines': items_dict['Basin Keep Vending Machine Unlock', 1],
    'basinItems': items_dict['Basin Keep Items Unlock', 1],
    'basinWeapons': items_dict['Basin Keep Weapons Unlock', 1],
    'basinMushroom': items_dict['Calzone Shop Unlock', 1],
    'sapphireWeapons': items_dict['Sapphire Ridge Weapons Unlock', 1],
    'sapphireItems': items_dict['Sapphire Ridge Items Unlock', 1],
}

shop_unlock_by_shop_and_id = {
    ('rookieHarborItems', 1): items_dict['Rookie Harbor Items - Sandwich Slot Unlock', 1],
    ('rookieHarborItems', 27): items_dict['Rookie Harbor Items - Hi-Sandwich Slot Unlock', 1],
    ('rookieHarborItems', 2): items_dict['Rookie Harbor Items - Green Leaf Tea Slot Unlock', 1],
    ('rookieHarborItems', 366): items_dict['Rookie Harbor Items - Just Water Slot Unlock', 1],
    ('rookieHarborItems', 64): items_dict['Rookie Harbor Items - Spicy Bun Slot Unlock', 1],
    ('rookieHarborItems', 70): items_dict['Rookie Harbor Items - Fruit Drink Slot Unlock', 1],
    ('rookieHarborItems', 73): items_dict['Rookie Harbor Items - Rice Cracker Slot Unlock', 1],
    ('rookieHarborItems', 67): items_dict['Rookie Harbor Items - Veggie Sticks Slot Unlock', 1],
    ('rookieHarborItems', 353): items_dict['Rookie Harbor Items (Post-Blue Ice) - Kebab Roll Slot Unlock', 1],
    ('rookieHarborItems', 355): items_dict['Rookie Harbor Items (Post-Blue Ice) - Meaty Risotto Slot Unlock', 1],
    ('rookieHarborItems', 110): items_dict['Rookie Harbor Items (Post-Red Flame) - Bergen Ice Cream Slot Unlock', 1],
    ('rookieHarborItems', 165): items_dict['Rookie Harbor Items (Post-Red Flame) - Sweet Lemonjuice Slot Unlock', 1],
    ('rookieHarborItems', 290): items_dict['Rookie Harbor Items (Post-Green Seed) - Salted Peanuts Slot Unlock', 1],
    ('rookieHarborItems', 291): items_dict["Rookie Harbor Items (Post-Green Seed) - Cup o' Coffee Slot Unlock", 1],
    ('rookieHarborItems', 331): items_dict['Rookie Harbor Items (Post-Green Seed) - Snack Mix Slot Unlock', 1],
    ('rookieHarborWeapons', 31): items_dict['Rookie Harbor Weapons - Bronze Goggles Slot Unlock', 1],
    ('rookieHarborWeapons', 29): items_dict['Rookie Harbor Weapons - Bronze Edge Slot Unlock', 1],
    ('rookieHarborWeapons', 30): items_dict['Rookie Harbor Weapons - Bronze Mail Slot Unlock', 1],
    ('rookieHarborWeapons', 32): items_dict['Rookie Harbor Weapons - Bronze Boots Slot Unlock', 1],
    ('rookieHarborWeapons', 118): items_dict['Rookie Harbor Weapons - Iron Goggles Slot Unlock', 1],
    ('rookieHarborWeapons', 113): items_dict['Rookie Harbor Weapons - Iron Edge Slot Unlock', 1],
    ('rookieHarborWeapons', 122): items_dict['Rookie Harbor Weapons - Iron Mail Slot Unlock', 1],
    ('rookieHarborWeapons', 121): items_dict['Rookie Harbor Weapons - Iron Boots Slot Unlock', 1],
    ('rookieHarborWeapons', 264): items_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Goggles Slot Unlock', 1],
    ('rookieHarborWeapons', 266): items_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Edge Slot Unlock', 1],
    ('rookieHarborWeapons', 268): items_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Mail Slot Unlock', 1],
    ('rookieHarborWeapons', 270): items_dict['Rookie Harbor Weapons (Post-Red Flame) - Silver Boots Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 204): items_dict['Rookie Harbor North Weapons - Steel Goggles Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 205): items_dict['Rookie Harbor North Weapons - Steel Edge Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 206): items_dict['Rookie Harbor North Weapons - Steel Mail Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 207): items_dict['Rookie Harbor North Weapons - Steel Boots Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 264): items_dict['Rookie Harbor North Weapons - Silver Goggles Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 266): items_dict['Rookie Harbor North Weapons - Silver Edge Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 268): items_dict['Rookie Harbor North Weapons - Silver Mail Slot Unlock', 1],
    ('rookieHarborWeaponsNorth', 270): items_dict['Rookie Harbor North Weapons - Silver Boots Slot Unlock', 1],
    ('rookieHarborTara', 1): items_dict["Tara's Shop - Sandwich Slot Unlock", 1],
    ('rookieBacker', 382): items_dict['Rookie Harbor Backer Items - Rising Super Star Slot Unlock', 1],
    ('rookieBacker', 490): items_dict['Rookie Harbor Backer Items - Dk Pepper Slot Unlock', 1],
    ('rookieBacker', 491): items_dict['Rookie Harbor Backer Items - Cheese Spaetzle Slot Unlock', 1],
    ('rookieBacker', 315): items_dict['Rookie Harbor Backer Items - Maultasche Slot Unlock', 1],
    ('rookieBacker', 493): items_dict['Rookie Harbor Backer Items - Durian Slot Unlock', 1],
    ('rookieBacker', 494): items_dict['Rookie Harbor Backer Items - PengoPop Slot Unlock', 1],
    ('rookieBacker', 495): items_dict['Rookie Harbor Backer Items - Spicy Beat-0-Type Slot Unlock', 1],
    ('rookieBacker', 316): items_dict['Rookie Harbor Backer Items - Werewolf Stick Slot Unlock', 1],
    ('rookieBacker', 516): items_dict['Rookie Harbor Backer Items - Mooncake Slot Unlock', 1],
    ('rookieBacker', 496): items_dict['Rookie Harbor Backer Items - Guacamole Toast Slot Unlock', 1],
    ('rookieBacker', 551): items_dict['Rookie Harbor Backer Items - Willis Waldmahl Slot Unlock', 1],
    ('rookieBacker', 637): items_dict['Rookie Harbor Backer Items - Pumpkin Spice Cof. Slot Unlock', 1],
    ('bergenVillageItems', 1): items_dict['Bergen Village Items - Sandwich Slot Unlock', 1],
    ('bergenVillageItems', 27): items_dict['Bergen Village Items - Hi-Sandwich Slot Unlock', 1],
    ('bergenVillageItems', 2): items_dict['Bergen Village Items - Green Leaf Tea Slot Unlock', 1],
    ('bergenVillageItems', 366): items_dict['Bergen Village Items - Just Water Slot Unlock', 1],
    ('bergenVillageItems', 64): items_dict['Bergen Village Items - Spicy Bun Slot Unlock', 1],
    ('bergenVillageItems', 70): items_dict['Bergen Village Items - Fruit Drink Slot Unlock', 1],
    ('bergenVillageItems', 73): items_dict['Bergen Village Items - Rice Cracker Slot Unlock', 1],
    ('bergenVillageItems', 67): items_dict['Bergen Village Items - Veggie Sticks Slot Unlock', 1],
    ('bergenVillageItems', 353): items_dict['Bergen Village Items (Post-Blue Ice) - Kebab Roll Slot Unlock', 1],
    ('bergenVillageItems', 355): items_dict['Bergen Village Items (Post-Blue Ice) - Meaty Risotto Slot Unlock', 1],
    ('bergenVillageItems', 110): items_dict['Bergen Village Items (Post-Red Flame) - Bergen Ice Cream Slot Unlock', 1],
    ('bergenVillageItems', 165): items_dict['Bergen Village Items (Post-Red Flame) - Sweet Lemonjuice Slot Unlock', 1],
    ('bergenVillageItems', 290): items_dict['Bergen Village Items (Post-Green Seed) - Salted Peanuts Slot Unlock', 1],
    ('bergenVillageItems', 291): items_dict["Bergen Village Items (Post-Green Seed) - Cup o' Coffee Slot Unlock", 1],
    ('bergenVillageItems', 331): items_dict['Bergen Village Items (Post-Green Seed) - Snack Mix Slot Unlock', 1],
    ('bergenVillageWeapons', 118): items_dict['Bergen Village Weapons - Iron Goggles Slot Unlock', 1],
    ('bergenVillageWeapons', 113): items_dict['Bergen Village Weapons - Iron Edge Slot Unlock', 1],
    ('bergenVillageWeapons', 122): items_dict['Bergen Village Weapons - Iron Mail Slot Unlock', 1],
    ('bergenVillageWeapons', 121): items_dict['Bergen Village Weapons - Iron Boots Slot Unlock', 1],
    ('bergenHermit', 77): items_dict["Hermit's Hut - Chili Con Carne Slot Unlock", 1],
    ('bergenHermit', 165): items_dict["Hermit's Hut - Sweet Lemonjuice Slot Unlock", 1],
    ('bergenHermit', 3): items_dict["Hermit's Hut - Sweet Berry Tea Slot Unlock", 1],
    ('bakiItems', 1): items_dict["Ba'kii Kum Items - Sandwich Slot Unlock", 1],
    ('bakiItems', 27): items_dict["Ba'kii Kum Items - Hi-Sandwich Slot Unlock", 1],
    ('bakiItems', 2): items_dict["Ba'kii Kum Items - Green Leaf Tea Slot Unlock", 1],
    ('bakiItems', 366): items_dict["Ba'kii Kum Items - Just Water Slot Unlock", 1],
    ('bakiItems', 64): items_dict["Ba'kii Kum Items - Spicy Bun Slot Unlock", 1],
    ('bakiItems', 70): items_dict["Ba'kii Kum Items - Fruit Drink Slot Unlock", 1],
    ('bakiItems', 73): items_dict["Ba'kii Kum Items - Rice Cracker Slot Unlock", 1],
    ('bakiItems', 67): items_dict["Ba'kii Kum Items - Veggie Sticks Slot Unlock", 1],
    ('bakiItems', 110): items_dict["Ba'kii Kum Items - Bergen Ice Cream Slot Unlock", 1],
    ('bakiItems', 165): items_dict["Ba'kii Kum Items - Sweet Lemonjuice Slot Unlock", 1],
    ('bakiItems', 353): items_dict["Ba'kii Kum Items (Post-Blue Ice) - Kebab Roll Slot Unlock", 1],
    ('bakiItems', 355): items_dict["Ba'kii Kum Items (Post-Blue Ice) - Meaty Risotto Slot Unlock", 1],
    ('bakiItems', 290): items_dict["Ba'kii Kum Items (Post-Green Seed) - Salted Peanuts Slot Unlock", 1],
    ('bakiItems', 291): items_dict["Ba'kii Kum Items (Post-Green Seed) - Cup o' Coffee Slot Unlock", 1],
    ('bakiItems', 331): items_dict["Ba'kii Kum Items (Post-Green Seed) - Snack Mix Slot Unlock", 1],
    ('bakiWeapons', 118): items_dict["Ba'kii Kum Weapons - Iron Goggles Slot Unlock", 1],
    ('bakiWeapons', 113): items_dict["Ba'kii Kum Weapons - Iron Edge Slot Unlock", 1],
    ('bakiWeapons', 122): items_dict["Ba'kii Kum Weapons - Iron Mail Slot Unlock", 1],
    ('bakiWeapons', 121): items_dict["Ba'kii Kum Weapons - Iron Boots Slot Unlock", 1],
    ('bakiWeapons', 204): items_dict["Ba'kii Kum Weapons - Steel Goggles Slot Unlock", 1],
    ('bakiWeapons', 205): items_dict["Ba'kii Kum Weapons - Steel Edge Slot Unlock", 1],
    ('bakiWeapons', 206): items_dict["Ba'kii Kum Weapons - Steel Mail Slot Unlock", 1],
    ('bakiWeapons', 207): items_dict["Ba'kii Kum Weapons - Steel Boots Slot Unlock", 1],
    ('basinVendingMachines', 1): items_dict['Basin Keep Vending Machine - Sandwich Slot Unlock', 1],
    ('basinVendingMachines', 27): items_dict['Basin Keep Vending Machine - Hi-Sandwich Slot Unlock', 1],
    ('basinVendingMachines', 2): items_dict['Basin Keep Vending Machine - Green Leaf Tea Slot Unlock', 1],
    ('basinVendingMachines', 366): items_dict['Basin Keep Vending Machine - Just Water Slot Unlock', 1],
    ('basinVendingMachines', 64): items_dict['Basin Keep Vending Machine - Spicy Bun Slot Unlock', 1],
    ('basinVendingMachines', 70): items_dict['Basin Keep Vending Machine - Fruit Drink Slot Unlock', 1],
    ('basinVendingMachines', 73): items_dict['Basin Keep Vending Machine - Rice Cracker Slot Unlock', 1],
    ('basinVendingMachines', 67): items_dict['Basin Keep Vending Machine - Veggie Sticks Slot Unlock', 1],
    ('basinVendingMachines', 110): items_dict['Basin Keep Vending Machine - Bergen Ice Cream Slot Unlock', 1],
    ('basinVendingMachines', 165): items_dict['Basin Keep Vending Machine - Sweet Lemonjuice Slot Unlock', 1],
    ('basinVendingMachines', 290): items_dict['Basin Keep Vending Machine - Salted Peanuts Slot Unlock', 1],
    ('basinVendingMachines', 291): items_dict["Basin Keep Vending Machine - Cup o' Coffee Slot Unlock", 1],
    ('basinVendingMachines', 331): items_dict['Basin Keep Vending Machine - Snack Mix Slot Unlock', 1],
    ('basinVendingMachines', 353): items_dict['Basin Keep Vending Machine - Kebab Roll Slot Unlock', 1],
    ('basinVendingMachines', 355): items_dict['Basin Keep Vending Machine - Meaty Risotto Slot Unlock', 1],
    ('basinItems', 1): items_dict['Basin Keep Items - Sandwich Slot Unlock', 1],
    ('basinItems', 27): items_dict['Basin Keep Items - Hi-Sandwich Slot Unlock', 1],
    ('basinItems', 2): items_dict['Basin Keep Items - Green Leaf Tea Slot Unlock', 1],
    ('basinItems', 366): items_dict['Basin Keep Items - Just Water Slot Unlock', 1],
    ('basinItems', 353): items_dict['Basin Keep Items - Kebab Roll Slot Unlock', 1],
    ('basinItems', 355): items_dict['Basin Keep Items - Meaty Risotto Slot Unlock', 1],
    ('basinItems', 64): items_dict['Basin Keep Items - Spicy Bun Slot Unlock', 1],
    ('basinItems', 70): items_dict['Basin Keep Items - Fruit Drink Slot Unlock', 1],
    ('basinItems', 73): items_dict['Basin Keep Items - Rice Cracker Slot Unlock', 1],
    ('basinItems', 67): items_dict['Basin Keep Items - Veggie Sticks Slot Unlock', 1],
    ('basinItems', 110): items_dict['Basin Keep Items - Bergen Ice Cream Slot Unlock', 1],
    ('basinItems', 165): items_dict['Basin Keep Items - Sweet Lemonjuice Slot Unlock', 1],
    ('basinItems', 290): items_dict['Basin Keep Items - Salted Peanuts Slot Unlock', 1],
    ('basinItems', 291): items_dict["Basin Keep Items - Cup o' Coffee Slot Unlock", 1],
    ('basinItems', 331): items_dict['Basin Keep Items - Snack Mix Slot Unlock', 1],
    ('basinWeapons', 264): items_dict['Basin Keep Weapons - Silver Goggles Slot Unlock', 1],
    ('basinWeapons', 266): items_dict['Basin Keep Weapons - Silver Edge Slot Unlock', 1],
    ('basinWeapons', 268): items_dict['Basin Keep Weapons - Silver Mail Slot Unlock', 1],
    ('basinWeapons', 270): items_dict['Basin Keep Weapons - Silver Boots Slot Unlock', 1],
    ('basinWeapons', 265): items_dict['Basin Keep Weapons - Titan Goggles Slot Unlock', 1],
    ('basinWeapons', 267): items_dict['Basin Keep Weapons - Titan Edge Slot Unlock', 1],
    ('basinWeapons', 269): items_dict['Basin Keep Weapons - Titan Mail Slot Unlock', 1],
    ('basinWeapons', 271): items_dict['Basin Keep Weapons - Titan Boots Slot Unlock', 1],
    ('basinMushroom', 346): items_dict['Calzone Shop - One Up Slot Unlock', 1],
    ('sapphireWeapons', 265): items_dict['Sapphire Ridge Weapons - Titan Goggles Slot Unlock', 1],
    ('sapphireWeapons', 267): items_dict['Sapphire Ridge Weapons - Titan Edge Slot Unlock', 1],
    ('sapphireWeapons', 269): items_dict['Sapphire Ridge Weapons - Titan Mail Slot Unlock', 1],
    ('sapphireWeapons', 271): items_dict['Sapphire Ridge Weapons - Titan Boots Slot Unlock', 1],
    ('sapphireWeapons', 393): items_dict['Sapphire Ridge Weapons - Cobalt Goggles Slot Unlock', 1],
    ('sapphireWeapons', 394): items_dict['Sapphire Ridge Weapons - Cobalt Edge Slot Unlock', 1],
    ('sapphireWeapons', 395): items_dict['Sapphire Ridge Weapons - Cobalt Mail Slot Unlock', 1],
    ('sapphireWeapons', 396): items_dict['Sapphire Ridge Weapons - Cobalt Boots Slot Unlock', 1],
    ('sapphireItems', 1): items_dict['Sapphire Ridge Items - Sandwich Slot Unlock', 1],
    ('sapphireItems', 27): items_dict['Sapphire Ridge Items - Hi-Sandwich Slot Unlock', 1],
    ('sapphireItems', 2): items_dict['Sapphire Ridge Items - Green Leaf Tea Slot Unlock', 1],
    ('sapphireItems', 366): items_dict['Sapphire Ridge Items - Just Water Slot Unlock', 1],
    ('sapphireItems', 353): items_dict['Sapphire Ridge Items - Kebab Roll Slot Unlock', 1],
    ('sapphireItems', 355): items_dict['Sapphire Ridge Items - Meaty Risotto Slot Unlock', 1],
    ('sapphireItems', 64): items_dict['Sapphire Ridge Items - Spicy Bun Slot Unlock', 1],
    ('sapphireItems', 70): items_dict['Sapphire Ridge Items - Fruit Drink Slot Unlock', 1],
    ('sapphireItems', 73): items_dict['Sapphire Ridge Items - Rice Cracker Slot Unlock', 1],
    ('sapphireItems', 67): items_dict['Sapphire Ridge Items - Veggie Sticks Slot Unlock', 1],
    ('sapphireItems', 110): items_dict['Sapphire Ridge Items - Bergen Ice Cream Slot Unlock', 1],
    ('sapphireItems', 165): items_dict['Sapphire Ridge Items - Sweet Lemonjuice Slot Unlock', 1],
    ('sapphireItems', 290): items_dict['Sapphire Ridge Items - Salted Peanuts Slot Unlock', 1],
    ('sapphireItems', 291): items_dict["Sapphire Ridge Items - Cup o' Coffee Slot Unlock", 1],
    ('sapphireItems', 331): items_dict['Sapphire Ridge Items - Snack Mix Slot Unlock', 1],
}